spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: admin
    enabled: true
    locations:
      - 'classpath:db/migration'
